### ISSUE TITLE
Event Marker issue

### ISSUE THREAD

**Issue by labteng** [Gowerlabs/lumomat#49]
Hi, I reopened my previous issue here as I seems not to do on the original post.
Please see my problem here:
https://github.com/Gowerlabs/lumomat/issues/47#issuecomment-1809594086

**Comment by samuelpowell** [comment]
@labteng this is a new issue so best to post all details here. Please can you provide an example file which triggers this behavior?

**Comment by labteng** [comment]
https://gocuhk-my.sharepoint.com/:u:/g/personal/siqigao_cuhk_edu_hk/EX0GbQ61qkdPvrVCUY_t6hIByOZ1MtThGuDaq5Kxdx3aOQ?e=arBA3l

The data with event marker is a bit large so I put it in a drive link . Please tell me if you cant download it. The markers are recorded successfully as the output .nirs data shows the event marker line in Homer 2, but somwhow for .snirf format, the Homer3 just cant load   the markers.

**Comment by nidadu** [comment]
@labteng thanks for the data. I had a look at it and found the following event markers: 
```
    mark     timestamp
    _____    _________

    {'A'}      3.184  
    {'A'}     42.284  
    {'A'}     81.419  
    {'A'}      120.5  
    {'A'}     159.57  
    {'A'}     198.62  
    {'A'}     237.72  
    {'A'}     276.86  
    {'A'}     315.96  
    {'A'}     355.02  
    {'A'}     394.11  
    {'A'}     433.19  
    {'A'}     472.28  
    {'A'}     511.38  
    {'A'}      550.5  
    {'E'}     588.29  
    {'D'}     588.31  
    {'\'}     588.33  
    {'r'}     588.35  
```
 Can you confirm that this is what you expect them to be?

In addition, can you confirm the steps to recreate your error using Homer3?

**Comment by labteng** [comment]
Yes. Those are my markers.

All I did was:
1. converted the .lufr to .snirf using the codes below:

data = LumoData('testA.lufr');

snirf = data.write_SNIRF('testA.snirf','time','explicit');

2. immediately called out Homer3 in the command line and let the Homer3 automatically load the .snirf data. 

3.No config file was added.

4. When the signal appeared, I could not find the event markers in the time windows, and the time windows can only show up to 6s.

**Comment by nidadu** [comment]
@labteng Thanks for the above. I can successfully recreate the warnings that you get. What I found was that Homer3 does not support the use of a backslash `\` as an event marker, so we would advise to use an alternative character.

In addition, the event markers that lumomat outputs are in seconds as per SNIRF specification. The data and aux data has the time units of `TimeUnit` which in this case is miliseconds. However, Homer3 does not properly process the time unit field and plots all data in the same time window without adjusting the units (as raised in https://github.com/BUNPC/Homer3/issues/45). This is why you can't see the event markers on the GUI - they are hiding in the first time frames, displayed incorrectly. 

If it would be helpful, we could adjust the package to output seconds by default for all data fields. This way the event markers and raw data would have the same time units on the Homer3 GUI.

**Comment by labteng** [comment]
Many thanks to your support. I would delete the slash in the markers file. Would you please send me a package that is able to convert the time scale as Homer 3 does? @nidadu

**Comment by samuelpowell** [comment]
@labteng please see [version 1.8.0](https://github.com/Gowerlabs/lumomat/releases/tag/v1.8.0) which will default to seconds for the time unit.

**Comment by labteng** [comment]
Many thanks! Everything works now!
