### ISSUE TITLE
sources and detectors could not be aligned to an Atlas

### ISSUE THREAD

**Issue by labteng** [Gowerlabs/lumomat#51]
Hello,

![image](https://github.com/Gowerlabs/lumomat/assets/116700366/010e4b5e-202b-4b73-978d-14cfad5c7ea3)

I am doing image reconstructions and trying to align my concentration data to atlas. I use AtlasViewer 2.4.4.0 and find it could not successfully load probe from my converted .snirf data (see the result). I am doing a temporal scanning while all of the probes are in vertical shape and do not align with the surface. Any functions that are related my probe will result in errors like:

Error using *
Incorrect dimensions for matrix multiplication. Check that the number of columns in the first
matrix matches the number of rows in the second matrix. To operate on each element of the
matrix individually, use TIMES (.*) for elementwise multiplication.

Error in registerProbe2Head (line 21)
probe.optpos_reg = optpos*T;

Error in AtlasViewerGUI>pushbuttonRegisterProbeToSurface_Callback (line 679)
probe = registerProbe2Head(probe, headvol, refpts);

Error in gui_mainfcn (line 95)
feval(varargin{:});

Error in AtlasViewerGUI (line 19)
gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)AtlasViewerGUI('pushbuttonRegisterProbeToSurface_Callback',hObject,eventdata,guidata(hObject))

Related documentation

Error while evaluating UIControl Callback.

I am wondering is it the problem of the AtlasViewer or our data?

Please check my data here if need:
https://gocuhk-my.sharepoint.com/:u:/g/personal/siqigao_cuhk_edu_hk/EX0GbQ61qkdPvrVCUY_t6hIByOZ1MtThGuDaq5Kxdx3aOQ?e=arBA3l

You can find the bug by using the code below to convert the .lufr into .snirf by lumomat (ver.1.8.0)and call out the AtlasViewerGUI (ver.2.4.4.0) in the command line immediately.

data = LumoData('testA.lufr');

snirf = data.write_SNIRF('testA.snirf', 'time', 'explicit');

**Comment by nidadu** [comment]
Hello @labteng. Unfortunately, I don't get the error when I load your data using your setup. Can you show me the exact steps that you take in AltasViewer?

The steps that I followed: open the GUI and then choose Tools->Probe->Load in AV. After selecting a SNIRF file, it loads the data with a prompt asking about the registration marks. I get a warning below, but I do not get your error.
```
WARNING: Loaded probe lacks registration data. In order to register it
to head surface you need to add registration data. You can manually add
registration data using SDgui application.
```
The warning can be fixed by either adding the registration data using SDgui or registering to head size on AtlasViewerGUI. We recommend you seek the AtlasViewer documentation for this.

**Comment by labteng** [comment]
Hi @nidadu, would you please try setting the current working directory to the data location, and then directly call out AtlasViewerGUI from matlab command line? After AtlasViewer loads the data automatically, you might see my bug.

I also try your method. The probes' distribution changes however, the location of every probe went a bit down and away from brain. Can you also check your result for that?

**Comment by nidadu** [comment]
Hi @labteng. Thanks for confirming.

I repeated your steps of setting the working directory to the data file location and calling AtlasViewer from the command line. I did not get any errors, and the optode positions were successfully loaded on the atlas. The positions were not aligned correctly, but that can be expected. The result was similar to that obtained with the method I described previously. As I mentioned above, one way to adjust the optode positions is to add the registration data. 

As I can't find anything wrong with lumomat in this case, I will close this issue. I would recommend reading through the AtlasViewer documentation to learn how to adjust the location of the probes on their software, or seek help through their appropriate channels. Alternatively, you could email Gowerlabs to ask for research support.

**Comment by labteng** [comment]
Thank you @nidadu.

About the registration data, I do have issues to follow up. Please see the new po I just created.
