### ISSUE TITLE
Register Probes to surface error: Incorrect dimensions for matrix multiplication.

### ISSUE THREAD

**Issue by labteng** [Gowerlabs/lumomat#52]
This is a follow up for my previous issue: https://github.com/Gowerlabs/lumomat/issues/51#issue-2009067598

As we just finished preprocessing by Homer3, we tried group results on AtlasViewerGUI again and hoped to see whether it could use the HRF to generate sensitivity. However, AtlasViewer failed to register probes to surface again and repeated the error "Incorrect dimensions for matrix multiplication". 

I was reminded that the registration data was not compulsory in AtlasViewerGUI for image reconstruction. This time the GUI does not require registration data anymore, and I could not load .SD elsewhere due to the deviates results as well. Therefore, I would like you to help me check the location matrix of the group result again. The package is a bit large. Please download the whole 'glm-test' file here: https://gocuhk-my.sharepoint.com/:f:/g/personal/siqigao_cuhk_edu_hk/Ek1yMQ5OYyJOh2-lpVtLedcB837zXKWN6EPXZg4dywap4g?e=lbyLqf

My system: win 11
software version: Matlab 2023b
                            Homer3 1.80.2
                            AtlasViewerGUI 2.44.0

My step: 1. set the 'glm-test' folder as the current working directory in Matlab.
               2. call out the AtlasViewGUI  in matlab cmd line
               3. click the "Register Probe to Surface " right below the head atlas
               4. you can see the error starts with "Incorrect dimensions for matrix multiplication" in the cmd.

**Comment by samuelpowell** [comment]
@labteng we cannot identify any actionable issue with lumomat and therefore will close this issue.  If you are able to demonstrate a problem with the package, please open a new issue.
