### ISSUE TITLE
Channel design issue with Homer 3

### ISSUE THREAD

**Issue by labteng** [Gowerlabs/lumomat#53]
Hi, I noticed that the .snirf data generated by Lumo cannot be properly read by Homer 3 in terms of the channel layout and channel index.

For instance, when two tiles are placed in separate L and R temporal locations, Homer 3 will present inter-channels connecting the two tiles. This means that a source will be linked to every detector on both tiles, resulting in numerous artificial channels. These channels do not actually exist during the recording in Lumo software. For example, source 4 connected to detector 2, S1 to D6, and so on.

![image](https://github.com/Gowerlabs/lumomat/assets/116700366/f16c67e0-34bf-472a-a9f9-e83f501cb5c4)

With more tiles added, you can see more and more fake channels are added in the Homer3, causing trouble to find the index of real channels. AtlasViewerGUI will also present channels in this way, so I guess that might also relate to my previous issues about image reconstruction. 
<img width="1280" alt="channel" src="https://github.com/Gowerlabs/lumomat/assets/116700366/d93c961c-57d2-4de7-a4ae-eb2c0126bb17">

When only using a single tile, this problem won't occur.
![image](https://github.com/Gowerlabs/lumomat/assets/116700366/d66e8b64-55b5-41d6-985b-f08fa3d9407d)

I checked the functions used in lumomat on channels, it looks like the channel information is loaded right from the layout file. As long as the layout file is correct, I am not sure why the .snirf is not corresponded to .lufr. 

Could you help me check this issue? As it really affects us doing by channel analysis and image reconstruction.

Step:

1. download the testing package: https://gocuhk-my.sharepoint.com/:f:/g/personal/siqigao_cuhk_edu_hk/EiQ5z3eZMU9JrgPzkRW_3VsBXG98dYIlhSwWtNIZnwB58A?e=px5Eb4
2. set folder 1T, 2T and 12T respectively as the working directory in the matlab cmd and call out the Homer3 immediately to load every snirf file. After Homer3 loads the file, you can see the channels on the right side.

system info:
win 11
software version: Matlab 2023b
Homer3 1.80.2
AtlasViewerGUI 2.44.0
Lumomat 18.0

**Comment by samuelpowell** [comment]
> For instance, when two tiles are placed in separate L and R temporal locations, Homer 3 will present inter-channels connecting the two tiles. This means that a source will be linked to every detector on both tiles,

This is the correct behaviour.

 LUMO can record both intra- and inter-tile channels across a cap. As such, we see no error in the data files nor the converted SNIRF files.

**Comment by labteng** [comment]
> > For instance, when two tiles are placed in separate L and R temporal locations, Homer 3 will present inter-channels connecting the two tiles. This means that a source will be linked to every detector on both tiles,
> 
> 
> 
> This is the correct behaviour.
> 
> 
> 
>  LUMO can record both intra- and inter-tile channels across a cap. As such, we see no error in the data files nor the converted SNIRF files.

I just got replied from Gowerlab support team. They confirmed that source can be seen by all the detectors but only closely enough will form channels.
![image](https://github.com/Gowerlabs/lumomat/assets/116700366/fdd2df99-f2a7-470e-9541-c9431f0af9b4)
In addition, when selecting two tiles on LumoX GUI, it would not indicate any inter channels between those two.

I am wondering why there is divergence between Homer and LumoX. So which one we should refer to? Thank you.

I will also forward this issue to the research support.

**Comment by samuelpowell** [comment]
I am closing this issue as it does not appear to relate to lumomat.

**Comment by labteng** [comment]
Is it possible for lumomat to include the intra tiles channels only？
@samuelpowell

**Comment by samuelpowell** [comment]
No this is not supported as inter-tile channels are required in most conceivable applications.
