### ISSUE TITLE
Compatibility with Homer2

### ISSUE THREAD

**Issue by nidadu** [Gowerlabs/lumomat#54]
The Homer2 user guide states that the following fields in the NIRS format need to be present as a minimum requirement:  `SD`, `d`, `t`, `s`, `ml`, and `aux` ([Page 4 in the Homer2 user guide](https://www.nmr.mgh.harvard.edu/martinos/software/homer/HOMER2_UsersGuide_121129.pdf)).

The lumomat NIRS output currently does not support the outputs of `aux` and `s` in the case of no event markers.

**Comment by samhforbes** [comment]
Here I get s but not aux, so this may have changed slightly

**Comment by samuelpowell** [comment]
@nidadu could you take @Giuseppe-1993 through this with the aim of getting a PR together?

**Comment by samuelpowell** [comment]
Fixed in #58, released in v1.9.0.
