### ISSUE TITLE
Number of detectors in nirs.SDMeadlist

### ISSUE THREAD

**Issue by cmbritto** [Gowerlabs/lumomat#55]
Hi,
 
I am reaching out with a question related to the SD structure. After converting the .lufr to .nirs file, and checking the SD structured and the Measlist, there should be 132 detectors per sensor. But when looking at column 2, skips values after 32 to 61 and 64 to 105 (see image below). Should this be happening? If not how can we fix this? In the SD file structure nSrcs is 99, and nDets is 132.
 
Let me know if there is further information we can provide.
 
Thank you so much for your time and I look forward to hearing from you.
 
Image 1:
![image](https://github.com/Gowerlabs/lumomat/assets/171174630/fccba872-8e6f-4ffa-8382-2b997040da14)

image 2:
![image (1)](https://github.com/Gowerlabs/lumomat/assets/171174630/01e231be-8e24-4152-8712-c002e4b8d898)

Image 3:
![image (2)](https://github.com/Gowerlabs/lumomat/assets/171174630/d6e79a4a-948e-4e6f-a1f6-c8b22104741f)

**Comment by samuelpowell** [comment]
@cmbritto whilst all LUMO systems can record in 'dense' acquistion mode, where channels are formed from every source and every detector, the default behaviour is to operate in 'sparse' acquistion mode, where very long channels are discarded.

As such the indexing you show above is perfectly normal, source index 1 forms channels with the nearby detectors of indices 1 ... 32, 61 ... 64, and so on. I expect that if you were to inspect the length of the channels (distance between sources and detectors) in this list, they would all be less than, e.g., 70mm.

Do let me know if this answers your question.

**Comment by samuelpowell** [comment]
@cmbritto since we have not heard back from you I'm going to assume that this answers your questions and close the issue. Please reopen if required.
