### ISSUE TITLE
SnirfClass structure and HOMER3

### ISSUE THREAD

**Issue by samhforbes** [Gowerlabs/lumomat#57]
Sorry this may be not the issue I think it is, but...
When I run write_SNIRF and save the output I get a structure that is compliant with how I read the SNIRF requirements (that is a formatVersion and a nirs folder, with the other arguments - data, probe, stim, aux - beneath the nirs directory).
However this file then doesn't get recognised by HOMER3 when I try to process it.

If I read it back in using SnirfLoad, the structure changes - the upper level nirs directory is gone, and data, stim etc are now in the upper level directory next to formatVersion. formatVersion has also changed to the snirfClass default of 1.0 instead of 1.1. In this conversion most data seems to survive, but the aux gets lost, which is why I think HOMER3 won't read it.

It's worth noting that the HOMER3 sample data (Brite fingertapping) retain the latter structure I mention above.

Is there a mismatch in expectations here that's causing HOMER3 to be unable to read this file?

I'll note I tried instead converting to NIRS, but as mentioned in another issue, I lose the aux there too, so can't use it.

**Comment by samhforbes** [comment]
Probably worth noting you can see the properties of the snirf class in HOMER3 here: https://github.com/fNIRS/snirf_homer3/blob/master/Snirf/SnirfClass.m

**Comment by samuelpowell** [comment]
@samhforbes our SNIRF output is compliant with the specification, as you note. Evidently something strange is going on here with HOMER3, we can look to see what is happening, though we may need to open some issues on their repository.

@nidadu @Giuseppe-1993 could you please try and reproduce this issue and report back?

**Comment by Giuseppe-1993** [comment]
I can confirm that this issue is fixed when using the latest release version of Homer3 ([v 1.87.0](https://github.com/BUNPC/Homer3/releases/tag/v1.87.0)). The snirf files are successfully recognised and loaded into Homer3.
