### ISSUE TITLE
enum.groups.id hardcoded to 0x2dfa95a94 if uid is numeric

### ISSUE THREAD

**Issue by HBaghdadi1995** [Gowerlabs/lumomat#9]
## brief

The title should be self explanitory

## Steps to recreate

1. call `data = LumoData(...)` with a `v0.5.0` `.lumo file`
2. type in `data.enum.groups.id`

**Comment by samuelpowell** [comment]
Good catch, this will get a bit more testing when layout/group uid cross-checking is implemented
